version: '3.5'

services:
    practice_db:
        container_name: practice_db
        ports:
            - "5431:5432"
        environment:
            - POSTGRES_PASSWORD=VupsenPupsen228
            - POSTGRES_USER=postgres
        image: postgres:15-alpine
        volumes:
            - ./init_db:/docker-entrypoint-initdb.d