version: '3.7'
services:
  postgres:
    container_name: practice_db
    build: .
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "VupsenPupsen228"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
      
  mongo_db:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    
        